language: python
python:
- '2.7'
notifications:
  slack:
    secure: hHTIcCdDThvRZk02/EeNC80Cmwyrq9S84WVDTHXF9Bt6yF/6vaME/3uUn3EQxZL6wuRC/5yt0l5vB0e9G+QjwX4yVKwCfWBF4lBDMblvROM5AiW366qnxjslPWTIop3AvYoK/ht7p8YrXD+bJdjNAYrVp2+QfD0egzyxAPV/ysmdiFFGOhvtoO0wkI6lEG0Gs7cKwj0rjA1fb5NXZ21M8nEux8rZMyoyl5H3HbhlIfUO15vVK3KZzQTxH+kT3Wo3YFd4Zmz2vKwqw6XR9r/8ZRnTOJHcIi0MUb0Pso3o5O4hNpnLUMAYTLYQomh+JXYhC6dg5kS03R0jDjkyOyTZ3GxcQ8iniIwMVlkrfvyqNT+aYdofQXBwAJAC7rIHnSY5xgU+R31+OpC19zbKf4Er6q+CQu0UsHPqEC6uH0avSPQtDOnRPvusPBvE+LNk5z0+CL4W3rqsOcZflrEfIfmRllcurcLMo6w+uVnYVD/I9VRl431Fo5OcKTDrY/KRNkTv/YYDzWZBo/xs0jBKMCRfvx6WjtXsHlhPjWA2HfmcdQvhUrq7eOr/knwk1HQReSyoq8SZqtH4lleUIAXUExm9vL7OXsoFg6KXpJh0ofFeQV6kpDUKWd6MZlEBTexojGSGvGvQK2vUq3nb8hNGuP2MJTJP/EqIwX1C/FMq+BjEgQA=
deploy:
  provider: heroku
  api_key:
    secure: b045RWseCje+jJzdenvsiQ32fNOPUoBYB/lpwEyi8SMIBYREPHNG8ArB9/0dKdRRqlwY+uTNsaRwdIgjEU2NhVKOgbfO/dFHARcj6RniEn36/nICRa1dYSOzPAgPl2jA3tTdxWUpoLC3lsQxyRbUSlZl9WE4sS7YBwt6dUjtJgUYggWMoRNtTe/bXnMcmOYEVmjyjOhjul5KINZjnHcDoz3cewi7YeC7rfnzDg1Tv2EgI8GKQCC0ojD/UzRo9269GGF0VSje2N7tu5ixUBjsSGBUpNqMl/ReI6AHTQ8ryCPxdIaE8V7VyKj4mEd1nkvgk/WV9kMCWzowP2vS90VHdW4nHQZzDMLSqjuaSMZRHMpR5mxq6GD9IsqHAT8S76cdgZSRUuFehh020j+wZ5E+2BTXLcYVHzi+CTkQCaD7vQ4MZt4Ryy0FhsBOpYiw+uQtvMizPCDfWzXIBpU9DeJagXCt9G1FR42T45psKmBap2EICpy/ITr3mpT2Bt2yvshth3urZwBgLx5k3R2jPlFb035A7kd6N0+F3QYqDwTP/FDe30LySLg323sqhyKZM16k9oAmFMVE2wstiorEjPpjs+fWyYPi+MijhSGFQHr5SVl06F3u9bj2OvENnFc6D5LlIGeGh4H6YMklITMkJVnwY2CswRmF5QMNjGzIjc0To6w=
  app: lr-cases-api-alpha
  on:
    repo: LandRegistry/cases-api
    branch: master
