language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: nosetests
deploy:
  provider: heroku
  api_key:
    secure: b045RWseCje+jJzdenvsiQ32fNOPUoBYB/lpwEyi8SMIBYREPHNG8ArB9/0dKdRRqlwY+uTNsaRwdIgjEU2NhVKOgbfO/dFHARcj6RniEn36/nICRa1dYSOzPAgPl2jA3tTdxWUpoLC3lsQxyRbUSlZl9WE4sS7YBwt6dUjtJgUYggWMoRNtTe/bXnMcmOYEVmjyjOhjul5KINZjnHcDoz3cewi7YeC7rfnzDg1Tv2EgI8GKQCC0ojD/UzRo9269GGF0VSje2N7tu5ixUBjsSGBUpNqMl/ReI6AHTQ8ryCPxdIaE8V7VyKj4mEd1nkvgk/WV9kMCWzowP2vS90VHdW4nHQZzDMLSqjuaSMZRHMpR5mxq6GD9IsqHAT8S76cdgZSRUuFehh020j+wZ5E+2BTXLcYVHzi+CTkQCaD7vQ4MZt4Ryy0FhsBOpYiw+uQtvMizPCDfWzXIBpU9DeJagXCt9G1FR42T45psKmBap2EICpy/ITr3mpT2Bt2yvshth3urZwBgLx5k3R2jPlFb035A7kd6N0+F3QYqDwTP/FDe30LySLg323sqhyKZM16k9oAmFMVE2wstiorEjPpjs+fWyYPi+MijhSGFQHr5SVl06F3u9bj2OvENnFc6D5LlIGeGh4H6YMklITMkJVnwY2CswRmF5QMNjGzIjc0To6w=
  app: lr-cases-api-alpha
  on:
    repo: LandRegistry/cases-api
    branch: master
notifications:
  slack:
    secure: vO5gPbV8JDYrkYse232UicrEIdYTxPOZpMBjUl+rA9Roh8vaavK3+5pQmYNQUZvRJPo+dM+yuR5bGkOLPrc5TuRZFNkp1Q9TzRUt0f2x/6F5ot1pCFetL8ycj8T3eU9LgJ2y0Xn8zE/CILOX0K1mz8+SFBHJWPJR3VrxFI0XeL6JWOGwdM4GCPUWBvbuTS5lqvC3TG72C3cnURlLm6kFWBuhiWbsqm9G57Ywh43x2XNpXbYvMFr6Wxcf7zemXkJ4/9qUqvdRm2uIuiSxIbfvp36jlK9KQSTkA5/M42aHCoK3U4OnoXkx6bi9Lrdh8P9fLEj0ZH0OP0BWXFMKwEevduoY+0Dsfmf82CXQ7msEpacYXvK9dVPXGVGZ9CjljobkBAVhDENTFKt6OgiLawSKyaGEG8rKv1oIG06/WDtwD5tJHQcIRf9kOzVAKNjVxb47OE218IfXu28YqrNHrPvwAD1K1+gO1Je3LcJ2c0Zm2RzXajxcB20N4riDlH8rny9kHDu4dSsN8Ro4C/+MzAjxsvMHU6X3mCU3rKCKWKgI9VQgsNjb1ReWZTtUvEDyKXtAj/oH/dhQrFIUWUQ2RsKZTl1NOhHwinwoUCjd13EZqyMbesthuoNXEV4nqajrHZBHnqhJJe0CWL4AW+DBqEpkowM63/oD0/S/uDPK0xxn+yQ=
