#!/usr/bin/env bash
# A sample Gemfile
source "https://rubygems.org"

# gem "rails"

gem 'cucumber', '2.0.0'
gem 'selenium-webdriver', '2.42.0'
gem 'capybara', '2.4.4'
gem 'w3c_validators', '1.2.0'
gem 'savon'
gem 'phantomjs', '1.9.8.0'
gem 'poltergeist', '1.6.0'
gem 'test-unit'
gem 'net-ssh'
gem 'json'
